- name: Test if vpnadmin user is accessible
  local_action: shell ssh vpnadmin@{{ inventory_hostname }} -i {{ansible_ssh_private_key_file}} -o StrictHostKeyChecking=no -o BatchMode=yes "echo success"
  ignore_errors: yes
  register: vpnadmin_account_enabled

- import_tasks: 1-do-once.yml
  when: vpnadmin_account_enabled.stdout != "success"