- name: Set Machine Hostname
  template: src=hostname.j2 dest=/etc/hostname
  become: true
  tags: init

- name: Add own record to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1 {{ hostname }}"
    state: present
  tags: init
  become: true

- name: Run hostname command to avoid restart
  raw: hostname {{ hostname }}
  tags: init
  become: true

